### ISSUE TITLE
WARNING: Illegal reflective access by com.google.inject.assistedinject.FactoryProvider2

### ISSUE THREAD

**Issue by davido** [google/guice#1321] opened 2020-05-06 04:18 UTC
I'm seeing this warning when starting Gerrit with Java11:

```
$ java -jar bazel-bin/release.war init -d ../test_site_gerrit_3.2 --batch --dev
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.assistedinject.FactoryProvider2 (file:/home/davido/.gerritcodereview/tmp/gerrit_6966619352392581698_app/guice-assistedinject-4.2.3.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of com.google.inject.assistedinject.FactoryProvider2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

The code has even "this isn't a public API" comment:

https://github.com/google/guice/blob/master/extensions/assistedinject/src/com/google/inject/assistedinject/FactoryProvider2.java#L900-L915

```java
// Note: this isn't a public API, but we need to use it in order to call default methods on (or
  // with) non-public types.  If it doesn't exist, the code falls back to a less precise check.
  private static final Constructor<MethodHandles.Lookup> methodHandlesLookupCxtor =
      findMethodHandlesLookupCxtor();

  private static Constructor<MethodHandles.Lookup> findMethodHandlesLookupCxtor() {
    try {
      Constructor<MethodHandles.Lookup> cxtor =
          MethodHandles.Lookup.class.getDeclaredConstructor(Class.class, int.class);
      cxtor.setAccessible(true);
      return cxtor;
    } catch (ReflectiveOperationException ignored) {
      // Ignore, the code falls back to a less-precise check if we can't create method handles.
      return null;
    }
  }
```

See also this upstream issue: [1].

[1] https://crbug.com/gerrit/12639

**Comment by ogregoire** [comment] 2020-10-30 13:52
I was kind of hoping this would be fixed by 5.0.0-BETA-1, but nope, it's still there.

**Comment by GedMarc** [comment] 2020-10-30 15:51
Please try with https://search.maven.org/artifact/com.guicedee.services/guice/1.0.19.13/jar 

you can also use a vast range of addons that are all "guiced" and JLink compatible https://search.maven.org/search?q=g:com.guicedee.services 

www.guicedee.com

**Comment by ogregoire** [comment] 2020-10-30 16:13
@GedMarc The issue is still present.

**Comment by GedMarc** [comment] 2020-10-30 16:27
@ogregoire can you double check your dependency hierarchy? Or paste it here?

**Comment by mcculls** [comment] 2020-10-30 19:03
Note that this warning comes from the `assisted-inject` extension, not the main guice library. That extension still has a piece of reflection to look for a `MethodHandles.Lookup` constructor and it's this that causes the warning not any use of AOP, etc.

**Comment by sameb** [comment] 2020-10-30 19:47
Relevant code is here: https://github.com/google/guice/blob/master/extensions/assistedinject/src/com/google/inject/assistedinject/FactoryProvider2.java#L896-L947 .  Note that the reason Guice needs to do this is because it needs to call default methods on (or with) non-public types. There was no way I could see to do this using the public API.  If someone can point out how to do this w/o using reflection, please speak up.

**Comment by mcculls** [comment] 2020-10-30 19:52
I can take a look this weekend

**Comment by mcculls** [comment] 2020-11-01 23:05
@sameb here's what I came up with as an initial spike: https://github.com/google/guice/pull/1448

**Comment by AdmirableTable** [comment] 2021-01-10 22:00
Encountered this issue while initializing Gerrit 3.3.1using JDK 12.0.1. Looks like the issue isn't fixed

**Comment by davido** [comment] 2021-01-10 22:16
> Encountered this issue while initializing Gerrit 3.3.1 using JDK 12.0.1. Looks like the issue isn't fixed

Correct.

**Closed** 2021-02-03 22:38 UTC
