### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by jaroslawr** [google/guice#1536] opened 2021-09-17 10:15 UTC
The rececently released Java 17 removed Unsafe.defineAnonymousClass(): https://bugs.openjdk.java.net/browse/JDK-8267178 

In effect Guice will use ChildClassDefiner where it previously used UnsafeClassDefiner, and will then fail when generating its proxy classes for non-public classes e.g. using @Inject on their constructor, with an error like this:

class XYZ$$EnhancerByGuice$$575108993 cannot access its superclass XYZ (XYZ$$EnhancerByGuice$$575108993 is in unnamed module of loader ChildClassDefiner$ChildLoader @72acb566; XYZ is in unnamed module of loader 'app')

If you trace down where this error comes from in the JDK, the inter-module boundaries are not even checked if the superclass is not public, so there is no chance of fixing this by adding module exports or opens to the codebase that is using Guice. Apparently Hidden Classes are the suggested replacement for Unsafe.defineAnonymousClass:

https://openjdk.java.net/jeps/371

**Comment by jaroslawr** [comment] 2021-09-17 10:19
(Related: https://github.com/google/guice/pull/1529)

**Comment by mcculls** [comment] 2021-09-17 10:43
Yes, this should be fixed by #1529 (I just need to add some documentation around the new defining process)

**Comment by GedMarc** [comment] 2021-09-17 10:59
Hey @mcculls 
In Java 17 the proxy classes are getting created in an unnamed module instead of the owning class module/ or the com.google.inject module (as with 11->16) 
 
The superclass access check is failing on the proxy class, problem doesn't exist in a lower JDK (except 12, where it popped up and vanished in JDK 13)

Previous behaviour that works
```
module {
opens my.package.that.injects to com.google.inject;
}
```
Required changes for JDK 17 (because of superclass access check)
```
module {
exports my.package.that.inject ; //this is now required because the proxy class is loaded into an unnamed module now)
opens my.package.that.injects to com.google.inject;
}
```

Exception 
```
Caused by: java.lang.IllegalAccessError: class za.co.uwe.assist.v5.web.SaveFarmSessionIntoScopeOnCallExit$$FastClassByGuice$$118282047 (in unnamed module @0x1fdd8364) cannot access class za.co.uwe.assist.v5.web.SaveFarmSessionIntoScopeOnCallExit (in module za.co.uwe.assist.v5.web) because module za.co.uwe.assist.v5.web does not export za.co.uwe.assist.v5.web to unnamed module @0x1fdd8364
	at za.co.uwe.assist.v5.web.SaveFarmSessionIntoScopeOnCallExit$$FastClassByGuice$$118282047.GUICE$TRAMPOLINE(<generated>)
	at za.co.uwe.assist.v5.web.SaveFarmSessionIntoScopeOnCallExit$$FastClassByGuice$$118282047.apply(<generated>)
	at com.google.guice@0.0.0_0-SNAPSHOT/com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	
```

Dropping a JDK version and the issue goes away xD 

```
======================
Full classname legend:
======================
SaveFarmSessionIntoScopeOnCallExit:                              "za.co.uwe.assist.v5.web.SaveFarmSessionIntoScopeOnCallExit"
SaveFarmSessionIntoScopeOnCallExit$$FastClassByGuice$$118282047: "za.co.uwe.assist.v5.web.SaveFarmSessionIntoScopeOnCallExit$$FastClassByGuice$$118282047"
========================
End of classname legend:
========================
```

**Comment by GedMarc** [comment] 2021-09-17 11:00
Forgot to mention - When doing this, the unsafe access exception disappears and this one pops up

**Comment by mcculls** [comment] 2021-09-17 11:36
@GedMarc can you share an example project or test that recreates the exception?

**Comment by GedMarc** [comment] 2021-09-17 12:02
Here we are :- 
[guiced17.zip](https://github.com/google/guice/files/7185400/guiced17.zip)

profile "raw" for replicating on automatic module names, profile "modular" for executions on pure modules (for jlink/jpackage distributions)


Modular results :-
```
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: IllegalAccessError: class Caller$$FastClassByGuice$$1904349 (in unnamed module @0x197d671) cannot access class Caller (in module guiced17) because module guiced17 does not export my.application.to to unnamed module @0x197d671
  at Caller.<init>(Caller.java:10)
  while locating Caller

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
Caller:                            "my.application.to.Caller"
Caller$$FastClassByGuice$$1904349: "my.application.to.Caller$$FastClassByGuice$$1904349"
========================
End of classname legend:
========================

	at com.google.guice@1.2.0.3-jre17-rc1/com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
	at com.google.guice@1.2.0.3-jre17-rc1/com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103)
	at com.google.guice@1.2.0.3-jre17-rc1/com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
	at guiced17/my.application.to.Caller.main(Caller.java:18)
Caused by: java.lang.IllegalAccessError: class my.application.to.Caller$$FastClassByGuice$$1904349 (in unnamed module @0x197d671) cannot access class my.application.to.Caller (in module guiced17) because module guiced17 does not export my.application.to to unnamed module @0x197d671
	at my.application.to.Caller$$FastClassByGuice$$1904349.GUICE$TRAMPOLINE(<generated>)
	at my.application.to.Caller$$FastClassByGuice$$1904349.apply(<generated>)
	at com.google.guice@1.2.0.3-jre17-rc1/com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.guice@1.2.0.3-jre17-rc1/com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.guice@1.2.0.3-jre17-rc1/com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.guice@1.2.0.3-jre17-rc1/com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.guice@1.2.0.3-jre17-rc1/com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
	... 2 more
```

Raw execution Results 

```
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: IllegalAccessError: class Caller$$FastClassByGuice$$1660256 (in unnamed module @0x27c86f2d) cannot access class Caller (in module guiced17) because module guiced17 does not export my.application.to to unnamed module @0x27c86f2d
  at Caller.<init>(Caller.java:10)
  while locating Caller

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
Caller:                            "my.application.to.Caller"
Caller$$FastClassByGuice$$1660256: "my.application.to.Caller$$FastClassByGuice$$1660256"
========================
End of classname legend:
========================

	at com.google.guice@5.0.1/com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
	at com.google.guice@5.0.1/com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103)
	at com.google.guice@5.0.1/com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
	at guiced17/my.application.to.Caller.main(Caller.java:18)
Caused by: java.lang.IllegalAccessError: class my.application.to.Caller$$FastClassByGuice$$1660256 (in unnamed module @0x27c86f2d) cannot access class my.application.to.Caller (in module guiced17) because module guiced17 does not export my.application.to to unnamed module @0x27c86f2d
	at my.application.to.Caller$$FastClassByGuice$$1660256.GUICE$TRAMPOLINE(<generated>)
	at my.application.to.Caller$$FastClassByGuice$$1660256.apply(<generated>)
	at com.google.guice@5.0.1/com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.guice@5.0.1/com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.guice@5.0.1/com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.guice@5.0.1/com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.guice@5.0.1/com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
	... 2 more
```

**Comment by mcculls** [comment] 2021-09-17 13:30
Thanks, so the issue with the module example is that recent JDKs disallow access to `sun.misc.Unsafe` from modules unless they `requires jdk.unsupported`.  Without this requires the `Unsafe` class is not available and Guice falls back to using a child classloader. Note if Guice is on the classpath, it can access `sun.misc.Unsafe` - so this is only an issue when Guice is on the module path either as an automatic module or a pure module.

For the pure module case adding `requires jdk.unsupported` to the Guice module should be enough.

For the automatic module case you can either add `requires jdk.unsupported` to the example module, or use `--add-modules jdk.unsupported` on the command-line. (As long as some module `requires jdk.unsupported` or it's added via the command-line then Guice running as an automatic module will be allowed to also access it.)

I'll have a think about how best to do this in the build (which will probably involve making it a pure module)

**Comment by GedMarc** [comment] 2021-09-17 14:16
Hmm I can't confirm that, 

I've added the requires clause to both the core as a pure module, and the consumer as an automatic module, the same exception - (Only in 17) - also to command line

![image](https://user-images.githubusercontent.com/5367513/133797318-6d980c0d-0dfb-403d-ba56-89217712fd56.png)


```
Caused by: java.lang.IllegalAccessError: class za.co.uwe.assist.v5.web.SaveFarmSessionIntoScopeOnCallExit$$FastClassByGuice$$114333740 (in unnamed module @0x403b2e0b) cannot access class za.co.uwe.assist.v5.web.SaveFarmSessionIntoScopeOnCallExit (in module za.co.uwe.assist.v5.web) because module za.co.uwe.assist.v5.web does not export za.co.uwe.assist.v5.web to unnamed module @0x403b2e0b
	at za.co.uwe.assist.v5.web.SaveFarmSessionIntoScopeOnCallExit$$FastClassByGuice$$114333740.GUICE$TRAMPOLINE(<generated>)
	at za.co.uwe.assist.v5.web.SaveFarmSessionIntoScopeOnCallExit$$FastClassByGuice$$114333740.apply(<generated>)
	at com.google.guice@0.0.0_0-SNAPSHOT/com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.guice@0.0.0_0-SNAPSHOT/com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
```
Removing the added exports and adding in the requires still ends with the same result

![image](https://user-images.githubusercontent.com/5367513/133797472-47df0c02-9b19-439a-8736-00686026d244.png)

I'm attaching the jar(zip) with the module-info updated to include jdk.unsupported, 
Can use the previous replicator with jdk.unsupported as well to produce the same exception

[guice-0.0.0_0-SNAPSHOT.zip](https://github.com/google/guice/files/7186339/guice-0.0.0_0-SNAPSHOT.zip)

**Comment by GedMarc** [comment] 2021-09-17 14:19
The module shade/build is configured here (maybe to look at to assist not sure) - https://github.com/GedMarc/GuicedEE-Services/tree/master/guice-core

**Comment by mcculls** [comment] 2021-09-17 14:37
@GedMarc have you pulled in the changes from #1529 ?

**Comment by GedMarc** [comment] 2021-09-17 14:46
i haven't sorry! let me do that quick

**Comment by GedMarc** [comment] 2021-09-18 11:29
@mcculls Purring like a kitten sir!

the requires clause only necessary on the guice module, otherwise everything looks good - 
checked (obviously all the default as well)
* aop & private modules
* generic types binding
* persistence modules
* servlet modules

Happy panda :) You're the man!

**Comment by GedMarc** [comment] 2021-09-18 11:33
putting the modular jar here with my module-info just incase a multi release jar becomes a thing (doesn't include error prone annotations)

[guice.zip](https://github.com/google/guice/files/7189811/guice.zip)

[module-info.zip](https://github.com/google/guice/files/7189812/module-info.zip)

**Comment by wendigo** [comment] 2021-10-05 08:01
@mcculls is there any plan to make a release that includes recent JDK17 related improvements in the near future?

**Comment by jhaber** [comment] 2021-11-08 22:12
Would it be possible to publish a new Guice release that includes #1529? I wasn't able to get our services to start up on Java 17 without those changes

**Comment by anthraxx** [comment] 2021-12-10 16:57
Can we pretty please get a new release out? :cat2:

**Comment by FreeGuwop** [comment] 2021-12-30 18:27
Can we put out a new release of Guice?

**Comment by anthraxx** [comment] 2022-01-20 15:57
@markmarch @ad-fu @java-team-github-bot Sorry for dropping yet another comment, but I hope the explicit mentions here bring in some progress.
There are life signs as commits in the tree, but the lack of a release is really a hard blocker and very painful currently. Can we pretty please get a new release so we can make use of the fixes? :crying_cat_face:

**Comment by markmarch** [comment] 2022-01-20 19:21
We are working on a new release but there are currently some test failures when running with Java 17.

@mcculls If you have time, can you look into some of the test failures since you are most familiar with the bytecode gen stuff and those tests failures all seem to be related to that?

With bazel installed, you can reproduce the issue with the following command from the root of the repo:

```
bazel test --java_runtime_version=remotejdk_17 //...
```

I'll also spend some time looking into this. 

The original plan is to migrate from maven to bazel then create a new release that also include some of the kotlin work we've done that hasn't been released but I probably will just cut a new release once the test failures are fixed and punt the bazel and kotlin work to next release.

**Comment by mcculls** [comment] 2022-01-20 20:19
Hi @markmarch some of those failing tests rely on parsing stack traces to verify what mechanism was used to call the method. Java17 hides certain types of frames by default, particularly frames relating to anonymous nest-mates, so you need to add `-XX:+UnlockDiagnosticVMOptions -XX:+ShowHiddenFrames` so those tests can find the frames they're looking for:

https://github.com/google/guice/blob/master/core/pom.xml#L104

Note this is just for test verification purposes - in everyday use you wouldn't worry about not seeing these frames in stack traces.

**Closed** 2022-01-25 01:05 UTC
